# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [12]:
mas = np.zeros(10, dtype=int)
mas[4] = 1
mas1 = mas.reshape(2,5)
mas1

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [44]:
mas2 = np.arange(10,50, dtype=int)
mas2 = np.flip(mas2)
# mas3 = mas2[np.ix_(*[range(1,i,2) for i in mas2.shape])]
even = mas2[slice(1, np.array(mas2).size, 2)]
even

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [ ]:
mas33 = np.array([[0,1,2],[3,4,5],[6,7,8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [55]:
mas432 = np.random.rand(4,3,2)
min432 = np.min(mas432)
max432 = np.max(mas432)
print ('Random array:' , mas432)
print ('Min = {}, Max = {}'.format(min432, max432))

Random array: [[[0.77103366 0.65489737]
  [0.97701855 0.73319091]
  [0.91479459 0.55425406]]

 [[0.46777871 0.69606565]
  [0.43575742 0.3172949 ]
  [0.76783768 0.98155688]]

 [[0.5755557  0.93224599]
  [0.98678136 0.10819342]
  [0.67378952 0.60479633]]

 [[0.97459109 0.2312553 ]
  [0.75087125 0.17251315]
  [0.67165163 0.46737679]]]
Min = 0.10819341541768457, Max = 0.9867813605147702


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [58]:
A64 = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20], [21,22,23,24]]
A43 = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
Res = np.dot(A64, A43)
Res

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330],
       [334, 392, 450],
       [422, 496, 570],
       [510, 600, 690]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [65]:
mas77 = np.random.randint(100, size=(7,7))
avg = np.average(mas77)
sd = np.std(mas77)
print("Array:\n", mas77)
print("Mean = {} standard deviation = {}".format(avg, sd))
print("Normalized array:\n", mas77/np.linalg.norm(mas77))

Array:
 [[68 93 36 78 98 76 95]
 [44 13 35 33 68 71 89]
 [32 99 94 81 61 42 75]
 [45 34 92 52 13  9 36]
 [85 18 32 37 63 63 78]
 [51 62 17 66  4 82 38]
 [84 43 91 41 98  6 36]]
Mean = 56.265306122448976 standard deviation = 27.923931299013095
Normalized array:
 [[0.15465293 0.21151063 0.08187508 0.17739601 0.22288217 0.1728474
  0.21605925]
 [0.10006955 0.029566   0.07960077 0.07505216 0.15465293 0.16147586
  0.2024134 ]
 [0.07277785 0.22515648 0.21378494 0.18421894 0.13873278 0.09552093
  0.17057309]
 [0.10234385 0.07732647 0.20923632 0.11826401 0.029566   0.02046877
  0.08187508]
 [0.19331617 0.04093754 0.07277785 0.08414939 0.14328139 0.14328139
  0.17739601]
 [0.1159897  0.14100709 0.03866323 0.15010432 0.00909723 0.18649324
  0.0864237 ]
 [0.19104186 0.09779524 0.20696201 0.09324662 0.22288217 0.01364585
  0.08187508]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [67]:
import pandas as pd
import matplotlib as mpl
import seaborn as sbs

### Загрузите датасет Tips из набора датасетов seaborn

In [69]:
tips = sbs.load_dataset("tips")

### Посмотрите на первые 5 строчек

In [101]:
tips[:5]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Узнайте сколько всего строчек и колонок в данных

In [71]:
tips.shape

(244, 7)

### Проверьте есть ли пропуски в данных

In [74]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


### Посмотрите на распределение числовых признаков

In [75]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Найдите максимальное значение 'total_bill'

In [77]:
tips['total_bill'].max()

50.81

### Найдите количество курящих людей

In [85]:
tips[tips['smoker'] == 'Yes']['smoker'].count()

93

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [113]:
tips.groupby('day').mean('total_bill').filter(items=['day', 'total_bill'])

total_bill
day             
Thur   17.682742
Fri    17.151579
Sat    20.441379
Sun    21.410000

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [112]:
med = tips['total_bill'].mean()
tips[tips['total_bill'] > med].groupby('sex').mean('tip').filter(items=['sex', 'tip'])

tip
sex             
Male    3.968028
Female  3.814286

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [122]:
ds2 = tips.copy()
ds2['smoker'] = np.where(ds2['smoker'] == 'No', 0, 1)
ds2[50:60]

total_bill   tip     sex  smoker  day    time  size
50       12.54  2.50    Male       0  Sun  Dinner     2
51       10.29  2.60  Female       0  Sun  Dinner     2
52       34.81  5.20  Female       0  Sun  Dinner     4
53        9.94  1.56    Male       0  Sun  Dinner     2
54       25.56  4.34    Male       0  Sun  Dinner     4
55       19.49  3.51    Male       0  Sun  Dinner     2
56       38.01  3.00    Male       1  Sat  Dinner     4
57       26.41  1.50  Female       0  Sat  Dinner     2
58       11.24  1.76    Male       1  Sat  Dinner     2
59       48.27  6.73    Male       0  Sat  Dinner     4

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.