# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [12]:
mas = np.zeros(10, dtype=int)
mas[4] = 1
mas1 = mas.reshape(2,5)
mas1

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [44]:
mas2 = np.arange(10,50, dtype=int)
mas2 = np.flip(mas2)
# mas3 = mas2[np.ix_(*[range(1,i,2) for i in mas2.shape])]
even = mas2[slice(1, np.array(mas2).size, 2)]
even

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [ ]:
mas33 = np.array([[0,1,2],[3,4,5],[6,7,8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [55]:
mas432 = np.random.rand(4,3,2)
min432 = np.min(mas432)
max432 = np.max(mas432)
print ('Random array:' , mas432)
print ('Min = {}, Max = {}'.format(min432, max432))

Random array: [[[0.77103366 0.65489737]
  [0.97701855 0.73319091]
  [0.91479459 0.55425406]]

 [[0.46777871 0.69606565]
  [0.43575742 0.3172949 ]
  [0.76783768 0.98155688]]

 [[0.5755557  0.93224599]
  [0.98678136 0.10819342]
  [0.67378952 0.60479633]]

 [[0.97459109 0.2312553 ]
  [0.75087125 0.17251315]
  [0.67165163 0.46737679]]]
Min = 0.10819341541768457, Max = 0.9867813605147702


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [58]:
A64 = [[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20], [21,22,23,24]]
A43 = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
Res = np.dot(A64, A43)
Res

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330],
       [334, 392, 450],
       [422, 496, 570],
       [510, 600, 690]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [65]:
mas77 = np.random.randint(100, size=(7,7))
avg = np.average(mas77)
sd = np.std(mas77)
print("Array:\n", mas77)
print("Mean = {} standard deviation = {}".format(avg, sd))
print("Normalized array:\n", mas77/np.linalg.norm(mas77))

Array:
 [[68 93 36 78 98 76 95]
 [44 13 35 33 68 71 89]
 [32 99 94 81 61 42 75]
 [45 34 92 52 13  9 36]
 [85 18 32 37 63 63 78]
 [51 62 17 66  4 82 38]
 [84 43 91 41 98  6 36]]
Mean = 56.265306122448976 standard deviation = 27.923931299013095
Normalized array:
 [[0.15465293 0.21151063 0.08187508 0.17739601 0.22288217 0.1728474
  0.21605925]
 [0.10006955 0.029566   0.07960077 0.07505216 0.15465293 0.16147586
  0.2024134 ]
 [0.07277785 0.22515648 0.21378494 0.18421894 0.13873278 0.09552093
  0.17057309]
 [0.10234385 0.07732647 0.20923632 0.11826401 0.029566   0.02046877
  0.08187508]
 [0.19331617 0.04093754 0.07277785 0.08414939 0.14328139 0.14328139
  0.17739601]
 [0.1159897  0.14100709 0.03866323 0.15010432 0.00909723 0.18649324
  0.0864237 ]
 [0.19104186 0.09779524 0.20696201 0.09324662 0.22288217 0.01364585
  0.08187508]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
import pandas as pd
import matplotlib as mpl
import seaborn as sb

### Загрузите датасет Tips из набора датасетов seaborn

### Посмотрите на первые 5 строчек

### Узнайте сколько всего строчек и колонок в данных

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.